### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by VictorBell** [CasperTheCat/MetahumanDNATools#3]
Hi, can you, please explain how it works? I thought that this is plugin for maya, for working with dna files but it builds like .exe and generates some files, help please

**Comment by CasperTheCat** [comment]
Hi Victor,

This repository was an attempt at understanding how MetaHumans DNA files worked, since it drives all joint and blendshape data in Maya and wasn't editable. Epic has recently opened their own library for this, however.
